language: node_js
node_js:
  - "stable"
services:
  - mongodb
install:
    - npm install
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - node Server.js
script: 
- pkill('node')
